<?
  // Set page title.
  $this->headTitle($this->translate('Access types'));
  
  // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/accesspermissions') . '">' . $this->transEsc('Administration') . '</a></li> <li class="active">' . $this->transEsc('Access permissions') . '</li>';
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Access permissions')?></h2>    
	
	<!-- ADDED BY sb174 ON 2018-08-13 -->
	<div class="">
		<?=$this->transEsc('access_instructions')?><br/>
    </div>
	<!-- END -->
	
	
<?
$access_types = $this->accessTypes;
$types_names = $this->types;
$roles = $this->roles;
?>

<? if ($this->action == '1'): ?>
<div class="alert alert-success">
  <strong>Success!</strong> Indicates a successful or positive action.
</div>
<? elseif ($this->action == '2'): ?>
<div class="alert alert-danger">
  <strong>Danger!</strong> Indicates a dangerous or potentially negative action.
</div>
<? elseif ($this->action == '3'): ?>
<div class="alert alert-danger">
  <strong>Danger!</strong> Anyone changes the file.
</div>
<? endif; ?>

<form method="post" action="/Acadmin/Accesspermissions" name="savePermissionsForm" id="savePermissionsForm">

  <table class="GeneratedTable">
    <thead>
      <tr>
        <th></th>
        <? for ($i = 0; $i < count($types_names); $i++) { ?>
        <th><?=$types_names[$i];?></th>
        <? } ?>
      </tr>
    </thead>
    <tbody>
      <? for ($j = 0; $j < count($access_types); $j++) { ?>
        <tr>
          <th><?=$access_types[$j];?></th>
          <? $cont = 0; ?>
          <? for ($k = 0; $k < count($types_names); $k++) { 
            if (in_array($access_types[$j], $roles[$k])) { ?>
            	<td><input type="checkbox" name="<?=$cont?>[]" value="<?=$access_types[$j];?>" checked></td>
            <? } else { ?>
            	<td><input type="checkbox" name="<?=$cont?>[]" value="<?=$access_types[$j];?>"></td>
            <? }
            $cont++;
           } ?>
        </tr>
      <? } ?>
    </tbody>
  </table>

<input type="hidden" name="save" id="save" value="0"/>
<input type="hidden" name="readDate" id="readDate" value="<?=$this->readDate?>"/>

<button id="savePermissions" type="button" class="btn btn-default">Save</button>

<?
$file = '/usr/local/vufind/local/config/vufind/access.ini';
if (file_exists($file)) {
	$afterDelDate = date ("F d Y H:i:s.", filemtime($file));
}
?>

</form>

    
  </div>
  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->render("acadmin/menu.phtml")?>
  </div>
  
</div>

<script>
$(document).ready(function(){

/* To save the data */

	$('#save').val("0");
	$("#savePermissions").click(function() {
	    $('#readDate').val("<?=$afterDelDate?>");
	    bootbox.confirm({
	        message: "Do you want to save the settings?",
	        buttons: {
	            confirm: {
	                label: 'Yes',
	                className: 'btn-success'
	            },
	            cancel: {
	                label: 'No',
	                className: 'btn-danger'
	            }
	        },
	        callback: function (result) {
	            if(result) {
	            	$('#save').val("1");
	            	$("#savePermissionsForm").submit();
	            }
	        }
	    });
	});
});
</script>

