<h1>Privacy Policy</h1>

<dl class="Content">
  <dd>
    <p>The 2011 European Union update to the United Kingdom's Privacy and Electronic Communications Regulations 2003 requires us to warn about the use of cookies on this site.</p>
   <p>The SOAS Library Catalogue uses cookies to manage logged-in sessions and search history features. You may delete and block all cookies from this site but certain features will not work.</p>
   <p>By using the library catalogue, you are agreeing to the use of cookies as described.</p>
   <p>More information can be found at this link: <a href="http://www.soas.ac.uk/utility/privacy-policy.html">http://www.soas.ac.uk/utility/privacy-policy.html</a></p>
  </dd>
</dl>
