<?
  // Set page title.
  $this->headTitle($this->translate('Location list main text'));
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/locations') . '">' . $this->transEsc('Administration') . '</a></li><li><a href="' . $this->url('acadmin/locations') . '">' . $this->transEsc('Location list') . '</a></li> <li class="active">' . $this->transEsc('Main text') . '</li>';
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Main text')?></h2>
        
        </br></br>
        
<?=$this->flashmessages()?>    
    
<form method="post" action="/Acadmin/Maintext" name="saveForm" id="saveForm">
<div class="form-group">
<label for="description"><?=$this->transEsc('Main text')?></label>
<textarea rows="5" cols="10000" class="form-control"  id="description" name="description" value="<?=$this->text['description']?>"><?=$this->text['description']?></textarea>
</div>
<input value="Save" id="save" name="save" type="submit" class="btn btn-customized"/>
</form>
</div>
<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->render("acadmin/menu.phtml")?>
</div>
</div>
