<h1>About</h1>

<ul class="HelpMenu">
  <li><a href="#Contents">Collections</a></li>
  <li><a href="#Software">Software</a></li>
  <li><a href="#Development">Development</a></li>
</ul>

<dl class="Content">
  <dt><a name="Contents"></a>Collections</dt>
  <dd>
    <p><a href="/">library.soas.ac.uk</a> finds records of books, periodicals, research articles from SOAS Library's catalogue, from <a href="http://eprints.soas.ac.uk">SOAS Research Online</a>, from <a href="http://digital.soas.ac.uk//">SOAS Digital Collections</a>, and from <a href="https://www.soas.ac.uk/library/archives/">SOAS Archives</a>. 
	<p>Copyright and other intellectual property rights in these web pages belongs to SOAS unless otherwise indicated. Where copyright belongs to SOAS, content on this website is licensed for use under a <a href="http://creativecommons.org/licenses/by-nc-nd/2.0/uk/">Creative Commons Attribution-Non-Commercial-No Derivative Works 2.0 UK: England & Wales Licence (CC BY-NC-ND 2.0)</a> unless the individual resource states otherwise.</p>
    <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/2.0/uk/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/2.0/uk/88x31.png" /></a></p>
  </dd>
  
  <dt><a name="Software"></a>Software</dt>
  <dd>
    <p>This library catalogue runs on VuFind version 3.1.2. <a href="https://vufind-org.github.io/vufind/">VuFind</a> is open-source search engine and resource discovery software for libraries, museums and archives. VuFind was designed by <a href="http://library.villanova.edu/">Villanova University's Falvey Memorial Library</a> and is distributed under the <a href="https://gnu.org/licenses/gpl.html">GNU General Public License</a>.</p>
    <p>Library data is stored in SOAS Library's OLE library management system, version 3.0.12. <a href="https://openlibraryenvironment.org/">OLE (Open Library Environment)</a> is an open-source library management system and is distributed under the <a href="http://opensource.org/licenses/ecl2.php">Educational Community License Version 2.0 (ECL-2.0)</a>.</p>
    <p>SOAS Digital Collections is powered by <a href= "http://sobekrepository.org/">SobekCM,</a> version 4.12. This system allows users to discover online resources via semantic and full-text searches as well as a variety of different browse mechanisms. This repository includes online metadata editing and online submissions in support of institutional repositories. SobekCM is released as open source software under the <a href="https://gnu.org/licenses/gpl.html">GNU GPL license</a> and can be downloaded from the <a href="https://sobekdigital.com">SobekCM Software Download Site</a>.</p>
	<p>SOAS Research Online is powered by EPrints 3.3.10. EPrints is free software developed at the School of Electronics and Computer Science at the University of Southampton, England.  The SOAS installation is managed by <a href="https://www.cosector.com/digital-services">CoSector, University of London</a>.
	</dd>
  <dt><a name="Development"></a>Development</dt>
  <dd>
    <p>SOAS Library's catalogue is managed by the <a href="mailto:library.systems@soas.ac.uk">Library Digital Services Team</a> and SOAS IT Department. All original code written by SOAS is available in our <a href="https://github.com/soas-library/vufind">GitHub repository</a>.</p> 
	<p>Some code was written by by <a href="http://www.scanbit.net/en">Scanbit</a>, a company devoted to creating technology based services for libraries, museums, archives and documentation centres based on Free and Open Source Software.</p>
  </dd>
</dl>
