<h1>Searching in non-Roman scripts</h1>

<ul class="HelpMenu">
  <li><a href="#Summary">Summary</a></li>
  <li><a href="#How to">How to search for material in non-Roman script</a></li>
  <li><a href="#What is transliteration">What is transliteration?</a></li>
</ul>

<dl class="Content">
  <dt><a name="Summary"></a>Summary</dt>
  <dd>
    <p>For searching items in non-Roman scripts in our catalogue, you need to transliterate the author, title or keyword, using the <a href="http://www.loc.gov/catdir/cpso/roman.html" data-lightbox-ignore target="_blank">Library of Congress Romanization Rules</a>.
</p>
    <p>There is no need to input the diacritics (small signs around a letter).</p>
    <p>You can search in the original script (Arabic, Chinese, Japanese, etc.) for all books acquired after 2000.</p>
  </dd>
  
  <dt><a name="How to"></a>How to search for material in non-Roman script</dt>
  <dd>
    <p>SOAS Library collects a wide range of materials in non-Roman scripts. Records for these languages in the library catalogue are transliterated (romanized). Since 2000, records for Arabic, Chinese, Hebrew, Japanese, Persian and a few other languages using non-Roman scripts, can be searched and displayed in either transliterated or original script.</p>
    <p>Books anterior to 2000 may or may not have original script included in their library record.</p>
  </dd>
  
  <dt><a name="What is transliteration"></a>What is transliteration?</dt>
  <dd>
    <p>A romanization or latinization is a system for representing a word or language with the Roman (Latin) alphabet, where the original word or language used a different writing system. Methods of romanization include <a href="https://www.soas.ac.uk/library/using/glossary/" data-lightbox-ignore target="_blank">transliteration</a>, representing written text, and transcription, representing the spoken word. 
    </p>
    <p><i>Examples of transliterated titles:</i>
    <pre class="code"><a href="/Search/Results?lookfor=%D8%AF%D9%8A%D9%88%D8%A7%D9%86+%D8%AE%D9%88%D8%A7%D8%AC%D9%87+%D8%AD%D8%A7%D9%81%D8%B8+%D8%B4%D9%8A%D8%B1%D8%A7%D8%B2%D9%89&type=AllFields&limit=20&sort=relevance">ديوان خواجه حافظ شيرازى</a> = <a href="/Search/Results?lookfor=D%C4%ABv%C4%81n-i+Khv%C4%81jah+H%CC%A3%C4%81fiz%CC%A3+Sh%C4%ABr%C4%81z%C4%AB&type=AllFields&limit=20&sort=relevance">Dīvān-i Khvājah Ḥāfiẓ Shīrāzī</a>

<a href="/Search/Results?lookfor=和訳花園天皇宸記&type=AllFields&limit=20&sort=relevance">和訳花園天皇宸記</a> = <a href="/Search/Results?lookfor=Wayaku+Hanazono+Tennō+shinki&type=AllFields&limit=20&sort=relevance">Wayaku Hanazono Tennō shinki</a>

<a href="/Search/Results?lookfor=近百年古城古墓發掘史&type=AllFields&limit=20&sort=relevance">近百年古城古墓發掘史</a> = <a href="/Search/Results?lookfor=Jin+bai+nian+gu+cheng+gu+mu+fa+jue+shi&type=AllFields&limit=20&sort=relevance">Jin bai nian gu cheng gu mu fa jue shi</a></pre>
    <p>At SOAS, we use the Library of Congress Romanization Rules to transliterate most of non-Roman scripts. See the tables at: <a href="http://www.loc.gov/catdir/cpso/roman.html" data-lightbox-ignore target="_blank">http://www.loc.gov/catdir/cpso/roman.html</a></p>
    <p>There are many existing transliteration norms for non-Roman scripts (see <a href="http://transliteration.eki.ee/" data-lightbox-ignore target="_blank">http://transliteration.eki.ee</a>), but most UK libraries use the Library of Congress rules.</p>
    <p>For more information, get in touch with the relevant <a href="https://www.soas.ac.uk/library/contact/subject-and-regional-librarians/" data-lightbox-ignore target="_blank">subject librarian at SOAS</a>.</p>
  </dd>
</dl>
