<?
  // Set page title.
  $this->headTitle($this->translate('Library locations'));
  
  // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/librarylocations') . '">' . $this->transEsc('Administration') . '</a></li> <li class="active">' . $this->transEsc('Library location') . '</li>';
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Library locations')?></h2>
<?=$this->flashmessages()?>   



<form method="post" action="/Acadmin/Deletelibrarylocation" name="deleteLibraylocationForm" id="deleteLibrayloationForm">

<div id="locationPanel">
<a  class="btn btn-customized" href="<?=$this->url('acadmin/librarylocation');?>"><?=$this->transEsc('Add')?></a>
<input value="Delete" id="delete" name="delete" type="submit" class="btn btn-customized"/> 
</div> 

<table class="GeneratedTable">
<thead>
<tr>
<th class="thLocation" style="width:10%!important;"></th>
<th class="thLocation"><?=$this->translate('Library Locations')?></th>
 </tr>
</thead>
<tbody>

<? foreach($this->locationLibraryList as $locationLibray){ ?>
	<tr>
	<td><input class="" type="checkbox" name="check[]" id="<?=$locationLibray['id_level']?>" value="<?=$locationLibray['id_level']?>"></td>
	<td><a href="<?=$this->url('acadmin/librarylocation').'?id_level='.$locationLibray['id_level']?>"><?=$locationLibray['name'];?></a></td>
	</tr>
<? } ?>

 </tbody>
</table>
</form>

  </div>
  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->render("acadmin/menu.phtml")?>
  </div>
  
</div>

