<? if(empty($this->layout()->breadcrumbs)): ?> 
      <div class="alert_news">
      <strong>
      <h3 class="font18">Library update:</h3>
      <p class="font12">Items on mobile shelves on Level F in the Library are unavailable until further notice due to damage to the floor and mobile units.  We will keep</p>
      <p class="font12">you informed about repairs and future access.</p>
   </strong>
  </div>
<? endif; ?>
