<?$account = $this->auth()->getManager(); ?>

<?
/* Access permissions */
$home_access = $account->userPermissions('Header: Home');
$about_access = $account->userPermissions('Header: About');
$feedback_access = $account->userPermissions('Header: Feedback');

?>		

<!--<div id="soft_launch_feedback" class="pull-right well hidden-xs"><strong>New Login Screen: 13/10/2015</strong><br />
Click the new Login link to sign into your SOAS Library account.<br />
Use your SOAS ID  (or for external users LW number) and password.
</div>-->

<link href="/themes/scb-soas/css/carousel/book.carousel.css" media="all" rel="stylesheet" type="text/css">

<div id="menu_general_new">
<div id="menu_top_new">
<div class="collapse navbar-collapse" id="header-collapse">
<ul role="navigation" class="nav navbar-nav navbar-left">
        <? if (!$home_access) { ?>
	        <li class="white_link"><a class="white_link" href="https://www.soas.ac.uk/library/"><?=$this->transEsc("HOME")?></a></li>
        <?}?>
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
              <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
              <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
            </a>
          </li>
        <? endif; ?>
        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a class="white_link" href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a class="white_link" href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
            <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a class="white_link" href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("My account")?></a>
            <? else: ?>
              <a class="white_link" href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a class="white_link" href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

</ul>
<ul role="navigation" class="nav navbar-nav navbar-right">

      <!--<? if ($feedback_access) { ?>
      	<li><a class="white_link" href="mailto:libenquiry@soas.ac.uk?Subject=<?=$this->transEsc('Contact SOAS Library')?>" target="_top"><?=$this->transEsc("Feedback")?></a></li></a></li>
      <? } else { ?>
		<li><a class="white_link" href="http://www.soas.ac.uk/library/contact/" title="<?=$this->transEsc('Contact SOAS Library')?>"><?=$this->transEsc("Feedback")?></a></li></a></li>
      <? } ?>-->
	  
        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="language dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a class="white_link" href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>
        
        <li class="white_link"><a class="white_link" class="menu_top" href="/Locationlist"><i class="fa fa-search" id="library_item_menu"></i><?=$this->transEsc("Locate library item")?></a></li>
        
        <? /*<li class="white_link"><a class="white_link" href="https://www.soas.ac.uk/library"><i class="fa fa-at" id="library_website"></i><?=$this->transEsc("Library Website")?></a></li>
        <li class="white_link"><a class="white_link" class="menu_top" href="https://www.soas.ac.uk/library/using/finding/off-site-materials/"><i class="fa fa-share" id="off_site_menu"></i><?=$this->transEsc("Off-site Materials")?></a></li>
        <li><a id="link_about" href="<?=$this->url('help-home')?>?topic=about" data-lightbox class="help-link" title="<?=$this->transEsc('About')?>"><?=$this->transEsc('About')?></a></li>
        */ ?>
</ul>

    </div>
</div>
</div>
