<? $account = $this->auth()->getManager(); ?>
<? $times_access = $account->userPermissions('Header: Opening Times Banner');?>
<? if(empty($this->layout()->breadcrumbs)): ?>
		<div class="alert_news pull-right-xs pull-right">
			<div class="logo-transp hidden-xs">
			</div>
		<strong class="home_text_short" style="float:left;">
		<!--<h3 class="fronth3 font18">Library term time opening hours:</h3>
		<p class="font12">Monday to Friday: 08:00 to 23:30<br/>
Saturday to Sunday: 10:30 to 23:30<br/><br/>
		<? if (!$times_access) :?>
			For further information, see
			<a href="https://www.soas.ac.uk/library/using/openingtimes/">https://www.soas.ac.uk/library/using/openingtimes/</a>
		<? else: ?>
			For further information, see https://www.soas.ac.uk/library/using/openingtimes/
		<?endif;?>
		</p>-->
                <h3 class="fronth3 font18">Library opening hours:</h3>
                <p class="font12">
                <? if (!$times_access) :?>
                        <a href="https://www.soas.ac.uk/library/using/openingtimes/">soas.ac.uk/library/using/openingtimes</a>
                <? else: ?>
                        https://www.soas.ac.uk/library/using/openingtimes/
                <?endif;?>
                </p>
                <h3 class="fronth3 font18">Library training & events:</h3>
                <p class="font12">
                <? if (!$times_access) :?>
                        <a href="https://www.soas.ac.uk/library/events/">soas.ac.uk/library/events</a>
                <? else: ?>
                        https://www.soas.ac.uk/library/events/
                <?endif;?>
                </p>
		<!--<h3 class="fronth3 font18">SOAS Library update:</h3>
      <p class="font12">The library catalogue will be unavailable between 11:00 and 12:00 on Tuesday 28th December 2017. Please complete your transactions before this time to avoid disappointment.<br/>
      <h3 class="fronth3 font18">SOAS Library Christmas opening hours:</h3>
      <p class="font12">The Library will be closed on Sunday 24th December, Monday 25th December, and Tuesday 26th December.<br/>
Full details of opening hours over the Christmas period are available at <a href="https://www.soas.ac.uk/library/using/openingtimes/">https://www.soas.ac.uk/library/using/openingtimes/</a>.</p>-->
      <!--<h3 class="fronth3 font18">Library Christmas opening hours:</h3>
      <p class="font12">18 – 22 Dec.: 09:00 – 23:30<br/>
23 – 31 Dec.: 10:30 – 23:30<br/>
CLOSED between 24 - 26 Dec. and 1 Jan.<br/>
Service desks will close earlier. For specific times see <a href="https://www.soas.ac.uk/library/using/openingtimes/">https://www.soas.ac.uk/library/using/openingtimes/</a>.</p>-->
      </strong>
 
      </div>
<? endif; ?>
