<? if(empty($this->layout()->breadcrumbs)): ?>
      <div class="alert_news pull-right-xs pull-right">
      <strong class="home_text_short" style="float:left;">
      <h3 class="fronth3 font18">SOAS Library term-time opening hours:</h3>
      <p class="font12">Monday to Friday 9am to 11:30pm<br/>
Saturday & Sunday 10:30 to 11:30pm</p>
      </strong>
      <div class="logo-transp hidden-xs">
      </div>
      </div>
<? endif; ?>


