<? if(empty($this->layout()->breadcrumbs)): ?>
      <div class="alert_news pull-right-xs pull-right">
      <strong class="home_text_short" style="float:left;">
      <!--<h3 class="fronth3 font18">Library term-time opening hours:</h3>
      <p class="font12">Monday to Friday 09:00 to 11:30<br/>
Saturday & Sunday 10:30 to 11:30</p>-->
      <h4>24-hour library opening</h4>
      <p class="font12">From 09:00 Monday 19th March to 01:00 Saturday 24th March.</br>
Logging in to renewals and fine payments on the library catalogue will be unavailable between 23:45 and 00:30.
      </p>
      <!--<h3 class="fronth3 font18">SOAS Library update:</h3>
      <p class="font12">The library catalogue will be unavailable between 11:00 and 12:00 on Tuesday 28th December 2017. Please complete your transactions before this time to avoid disappointment.<br/>
      <h3 class="fronth3 font18">SOAS Library Christmas opening hours:</h3>
      <p class="font12">The Library will be closed on Sunday 24th December, Monday 25th December, and Tuesday 26th December.<br/>
Full details of opening hours over the Christmas period are available at <a href="https://www.soas.ac.uk/library/using/openingtimes/">https://www.soas.ac.uk/library/using/openingtimes/</a>.</p>-->
      <!--<h3 class="fronth3 font18">Library Christmas opening hours:</h3>
      <p class="font12">18 – 22 Dec.: 09:00 – 23:30<br/>
23 – 31 Dec.: 10:30 – 23:30<br/>
CLOSED between 24 - 26 Dec. and 1 Jan.<br/>
Service desks will close earlier. For specific times see <a href="https://www.soas.ac.uk/library/using/openingtimes/">https://www.soas.ac.uk/library/using/openingtimes/</a>.</p>-->
      </strong>
      <div class="logo-transp hidden-xs">
      </div>
      </div>
<? endif; ?>


