<? $collectionType = $this->driver->userPermissions('DOAB');?>
<?
  if($loggedin = $this->auth()->isLoggedIn()) {
	$user_id = $loggedin->id;
	$loggedin = true;
  } else {
	$user_id = false;
  }

  $formatRoles = function ($roles) {
	if (count($roles) == 0) {
	  return '';
	}
	$that = $this;
	$translate = function ($str) use ($that) {
	  return $that->transEsc('CreatorRoles::' . $str);
	};
	return ' (' . implode(', ', array_unique(array_map($translate, $roles))) . ')';
  };
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
	 $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
	 $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3 img-col	hidden-xs">
	<div class="text-center">
	  <? /* Display thumbnail if appropriate: */ ?>
	  <? if($cover): ?>
		<?=$cover?>
	  <? endif; ?>

	  <? /* Display qrcode if appropriate: */ ?>
	  <? if($QRCode): ?>
		<span class="hidden-xs">
		  <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
		</span>
	  <? endif; ?>
	</div>

	<? // if you have a preview tab but want to move or remove the preview link
	   // from this area of the record view, this can be split into
	   // getPreviewData() (should stay here) and
	   // getPreviewLink() (can go in your desired tab) ?>
	<? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-9 info-col">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

	<h3 property="name"><?=rtrim(trim($this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())),"/")?></h3>
	
	 <? $lnkTitle = $this->driver->getLinkedTitle();if (!empty($lnkTitle)): ?>
   
		  <? foreach($lnkTitle as $field): ?>
			<h4><?=$this->escapeHtml($field)?></h4>
		  <? endforeach; ?>

	  <? endif; ?> 

	<? if ($this->userlist()->getMode() !== 'disabled'): ?>
	  <? /* Display the lists that this record is saved to */ ?>
	  <div class="savedLists hidden alert alert-info">
		<strong><?=$this->transEsc("Saved in")?>:</strong>
	  </div>
	<? endif; ?>
   
	<?
	// Set up convenience variables:
	$account = $this->auth()->getManager();
	$user = $account->isLoggedIn();
	$holdings = $this->driver->getRealTimeHoldings();
	$offlineMode = $this->ils()->getOfflineMode();
	// Account for replace_other_urls setting
	$openUrl = $this->openUrl($this->driver, 'record');
	$openUrlActive = $openUrl->isActive();
	// Account for replace_other_urls setting
	$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
	$count_holdings=0;
   ?>
   
<!-- HOLDINGS AND ITEMS BOX -->
   
<div class="holdings">

<!-- INTERNET RECORDS: DISPLAY URL (856u or 555u) -->
	<? if (!empty($urls) || $openUrl): ?>
		<table class="table table-responsive" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc("Internet")?>">
			<tr>
			<? $accessnote = $this->driver->getNote(); if (!empty($accessnote)): ?>
				<? foreach ($accessnote as $field): ?>
					<?if (stripos($field, 'SOAS') !== false): ?>
						<td><i><?= $this->escapeHtml($field)?></i>
						</td>
					<? endif; ?>
				<? endforeach; ?>
			<? endif; ?>
  
		<? if (!empty($urls)): ?>
			<? foreach ($urls as $current): ?>
				<? if($this->driver->getRegExpr($this->escapeHtml($current['desc']), $collectionType,$this->driver->getCollectionType()[0])): ?>										  
					<tr>
						<td><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a>
						</td>
					</tr>
				<? else: ?>
					<tr>
						<td><?=$this->transEsc("Not available")?></td>
					</tr>
				<? endif; ?>
			<? endforeach; ?>
		<? endif; ?>
		<? if ($openUrlActive): ?>
			<?=$openUrl->renderTemplate()?><br/>
		<? endif; ?>
		</table>
	<? endif; ?>
<!-- END INTERNET -->

</div>

<!-- END HOLDINGS AND ITEMS BOX -->

<!-- MAIN DETAILS TABLE -->
	
   <?/* Display Main Details */?>
	<table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
	
	  <? $statement = $this->driver->getStatement(); if (!empty($statement)): ?>
	  <tr>
		<th><?=$this->transEsc('Full Title')?>: </th>
		<td>
		  <? foreach($statement as $field): ?>
			<?=rtrim(trim($this->escapeHtml($field)),"/")?><br/>
		  <? endforeach; ?>
	<?$linkedstatement = $this->driver->getLinkedStatement(); if (!empty($linkedstatement)): ?>
		  <? foreach($linkedstatement as $field): ?>
			<?=$this->escapeHtml($field)?><br/>
		  <? endforeach; ?>
		<? endif; ?>
		</td>
	  </tr>
	  <? endif; ?>

	  <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
	  <tr>
		<th><?=$this->transEsc('Journal Title')?>:</th>
		<td>
		  <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
		  <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
		</td>
	  </tr>
	  <? endif; ?>

		   <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
	  <? if (!empty($nextTitles)): ?>
	  <tr>
		<th><?=$this->transEsc('New Title')?>: </th>
		<td>
		  <? foreach($nextTitles as $field): ?>
			<a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
		  <? endforeach; ?>
		</td>
	  </tr>
	  <? endif; ?>

	  <? if (!empty($prevTitles)): ?>
	  <tr>
		<th><?=$this->transEsc('Previous Title')?>: </th>
		<td>
		  <? foreach($prevTitles as $field): ?>
			<a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
		  <? endforeach; ?>
		</td>
	  </tr>
	  <? endif; ?>
	  
	  <? $alttitle = $this->driver->getAltTitle(); if (!empty($alttitle)): ?>
	  <tr>
		<th><?=$this->transEsc('Alternative Titles')?>: </th>
		<td>
		  <? foreach($alttitle as $field): ?>
			<a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
		  <? endforeach; ?>
		  <? $linkedalttitle = $this->driver->getLinkedTitleAlt(); if (!empty($linkedalttitle)): ?>
			<? foreach($linkedalttitle as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
			<? endforeach; ?>
		  <? endif; ?>
		</td>
	  </tr>
	  <? endif; ?>

   <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
	  <? if (isset($authors['main']) && !empty($authors['main'])): ?>
		<tr>
		  <th><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </th>
		  <td>
			<? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':', '?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><?=$formatRoles($roles)?></span></br><? endforeach; ?>
			
			<? $linkedauthor = $this->driver->getLinkedAuthor(); if (!empty($linkedauthor)): ?>
			<? foreach($linkedauthor as $field): ?>
			<a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a>
			<br />
			<? endforeach; ?>
		<? endif; ?>
		  </td>			 
		</tr>
	  <? endif; ?>

	 <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
		<tr>
		  <th><?=$this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Author' : 'Corporate Authors')?>: </th>
		  <td>
			<? $i = 0; foreach ($authors['corporate'] as $corporate => $roles): ?><?=($i++ == 0)?'':', '?><span property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $corporate)?>"><?=$this->escapeHtml($corporate)?></a><?=$formatRoles($roles)?></span></br><? endforeach; ?>
		  
		<? $linkedcorporate = $this->driver->getLinkedCorporate(); if (!empty($linkedcorporate)):?>
		 <? foreach ($linkedcorporate as $linkcorp): ?>
		 
		 <a href="<?=$this->record($this->driver)->getLink('author', $linkcorp)?>"><?= $this->escapeHtml($linkcorp)?></br>
		
		<?endforeach;?>
		<?endif;?>
	</td>
		</tr>
	  <? endif; ?>

	  <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
		<tr>
		  <th><?=$this->transEsc('Other Authors')?>: </th>
		  <td>
			<? $i = 0; foreach ($authors['secondary'] as $author => $roles): ?><?=($i++ == 0)?'':''?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><?=$formatRoles($roles)?></span></br><? endforeach; ?>
		  
		  
		  <? $linkedauthor2 = $this->driver->getLinkedAuthor2(); if (!empty($linkedauthor2)): ?>
			<? foreach ($linkedauthor2 as $linkauthor): ?>
		   
			<a href="<?=$this->record($this->driver)->getLink('author', $linkauthor)?>"><?= $this->escapeHtml($linkauthor)?></a></br>
			
			<? endforeach; ?>
		<?endif;?>	
	   </td>  
		</tr>
	  <? endif; ?>

	<? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
		<tr>
		  <th><?=$this->transEsc('Format')?>: </th>
		  <td><?=str_replace('class="', 'class="label label-info ', $this->record($this->driver)->getFormatList())?>
				 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		   <?if($this->driver->getElectronic()== "Electronic"):?>
				<span class="label label-info iconlabel electronic"><?=$this->transEsc("Electronic")?></span>
		   <?endif;?>
		  </td>
		</tr>
	  <? endif; ?>
	  
	  <? $rights = $this->driver->getRights(); if (!empty($rights)): ?>
		<tr>
			<th><?=$this->transEsc('License rights')?>: </th>
			<td>
				<? if (stripos($rights, 'http') !== false): ?>
					<a href="<?=$this->escapeHtml($rights)?>"><?=$this->escapeHtml($rights)?></a>
				<? else: ?>
					<?=$this->escapeHtml($rights)?>
				<? endif; ?>
			</td>
		</tr>
	  <? endif; ?>
	  
	  <? $journalholdings = $this->driver->getJournalHoldings(); if (!empty($journalholdings)): ?>
		<tr valign="top">
		  <th><?=$this->transEsc('Holdings')?>: </th>
		  <td><? foreach ($journalholdings as $field): ?><?= $this->escapeHtml($field)?><br/><? endforeach; ?></td>
		</tr>
	  <? endif; ?>

	   <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
	  <tr>
		<th><?=$this->transEsc('Edition')?>: </th>
		<td property="bookEdition">
		<?=$this->escapeHtml($edition)?>
		<br />
	</td>
	  </tr>
	  <? endif; ?>

 <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
	  <? if(!empty($recordLinks)): ?>
		<tr>
		  <th><?=$this->transEsc('Related Items')?>:</th>
		  <td>
			<? foreach ($recordLinks as $recordLink): ?>
			  <?=$this->transEsc($recordLink['title'])?>:
			  <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
			<? endforeach; ?>
			<? /* if we have record links, display relevant explanatory notes */
			  $related = $this->driver->getRelationshipNotes();
			  if (!empty($related)): ?>
				<? foreach ($related as $field): ?>
				  <?=$this->escapeHtml($field)?><br/>
				<? endforeach; ?>
			<? endif; ?>
		  </td>
		</tr>
	  <? endif; ?>

	  <? if ($this->usertags()->getMode() !== 'disabled'): ?>
		<? $tagList = $this->driver->getTags(); ?>
		<tr>
		  <th><?=$this->transEsc('Tags')?>: </th>
		  <td>
			<span class="pull-right">
			  <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
			</span>
			<div id="tagList">
			  <? if (count($tagList) > 0): ?>
				<? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
			  <? else: ?>
				<?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
			  <? endif; ?>
			</div>
		  </td>
		</tr>
	  <? endif; ?>
	</table>
	<?/* End Main Details */?>
	
<!-- END MAIN DETAILS TABLE -->
	
  </div>
</div>
</br></br>

<script>
function showAllHoldings() {
$( ".hidden_holdings" ).each(function() {
  $( this ).removeClass( "hidden_holdings" ).addClass( "hidden_holdings3" );
});

$( "#div_show_more" ).each(function() {
  $( this ).addClass( "hidden" );
});
$( "#div_show_less" ).each(function() {
  $( this ).removeClass( "hidden" );
});
}

function showLessHoldings() {
$( ".hidden_holdings3" ).each(function() {
	
  $( this ).removeClass( "hidden_holdings3" ).addClass( "hidden_holdings" );
  
  $( "#div_show_less" ).each(function() {
  $( this ).addClass( "hidden" );
});
$( "#div_show_more" ).each(function() {
  $( this ).removeClass( "hidden" );
});
});

}
</script>
