<? 
$account = $this->auth()->getManager();
$orderOffsiteMaterial_access = $account->userPermissions('Order offsite material');
?>

<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:

  $id = $this->driver->getUniqueId();
  $cart = $this->cart();
  $cartId = $this->driver->getSourceIdentifier() . '|' . $this->driver->getUniqueId();
?>
<ul class="nav nav-pills hidden-print col-sm-offset-3">
  <li><a class="sms-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" rel="nofollow"><i class="fa fa-mobile" aria-hidden="true"></i> <?=$this->transEsc('Text this')?></a></li>
  <li><a class="mail-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" rel="nofollow"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc('Email this')?></a></li>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow"><i class="fa fa-list-alt" aria-hidden="true"></i> <?=$this->transEsc('Export Record') ?></a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>
 
   <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li><a class="save-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" rel="nofollow"><i class="fa fa-star" aria-hidden="true"></i> <?=$this->transEsc('Add to favorites')?></a></li>
  <? endif; ?>
  
  <!--CUSTOM CODE ADDED FOR SOAS LIBRARY-->
  <? if (!$orderOffsiteMaterial_access): ?>
   <? $order = $this->driver->getOrderWith(); if (!empty($order) && count($order)>0 && !empty($order[0])): ?>
    <li><a id="sms-record" class="modal-link <?=$controllerClass?>" target="_blank" href="https://www.soas.ac.uk/library/archives/services/requesting-material/orders/" title="<?=$this->transEsc('Order archive material')?>"><i class="fa fa-share"></i> <?=$this->transEsc('Order archive material')?></a></li>
    <?endif;?>
  <?endif;?>
  <!--END-->


  <? if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-bookmark" aria-hidden="true"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  <? if ($cart->isActive()): ?>
    <li class="bookbag-menu">
      <input class="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a class="cart-add hidden<? if(!$cart->contains($cartId)): ?> correct<? endif ?>" href="#"><i class="fa fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a class="cart-remove hidden<? if($cart->contains($cartId)): ?> correct<? endif ?>"href="#"><i class="fa fa-minus-circle" aria-hidden="true"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>

  <? /* SCB Enquiry email */ ?>
  <li><a class="mail-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'EmailEnquiry')?>" rel="nofollow"><i class="fa fa-exclamation" aria-hidden="true"></i> <?=$this->transEsc('Report a problem')?></a></li>


</ul>