 <?
  $from = $this->classmark_from['name'];
  $to = $this->classmark_to['name'];
  $from_to = "";
  if($from == $to)
  	$from_to = $from;
  else
  	$from_to = substr($from,0,1)."-".substr($to,0,1); 
  ?> 
<?
  // Set page title.
  $this->headTitle($from_to.' '.$this->translate('Location List').': '.$this->translate('SOAS Library'));
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
 
   <h2><?=$from_to.' '.$this->translate('Location List').': '.$this->translate('SOAS Library')?></h2>
<?if(!empty($this->classmarks)):?>    
    <?foreach($this->classmarks as $classmark):?>
  <a id="<?=$classmark['id_classmark'];?>" <?if($this->id_classmark == $classmark['id_classmark']) { echo "class='classmark_letter bold'"; }else{ echo "class='classmark_letter'";}?>  href="<?='#'.$classmark['name']?>"><?=$classmark['name'];?></a>
  <?endforeach;?>

<?foreach($this->classmarks as $classmark):?>
<p class="classmark_name"><a id="<?=$classmark['name']?>" name="<?=$classmark['name']?>"></a><?=$classmark['name']?></p>
<p><?if($classmark['note'] !="")echo $classmark['note'];?></p>

<?$count_locations=0;?>
<?foreach($this->locations as $location):?>
<?if($classmark['id_classmark']==$location['id_classmark'])$count_locations=$count_locations+1;?>
<?endforeach;?>
<table class="GeneratedTable <?if($count_locations==0)echo 'hidden';?>">
 <thead>
 <tr>
<?if($classmark['periodical'] == '1'):?>
<th class="thLocation"><?=$this->translate('Per (except titles discontinued in or before 1990)')?></th>
<?else:?>
<th class="thLocation"><?=$this->translate('Class mark')?></th>
<?endif;?>
<th <?if($classmark['periodical'] == '1'){echo "class='grey_color thLocation'";}?>><?=$this->translate('Level')?></th>
<th><?=$this->translate('Book stack number')?></th>
<?if($classmark['periodical'] == '1'):?>
<th class="width5 grey_color thLocation"></th>
<th class="thLocation"><?=$this->translate('Per L Large size periodicals (all)')?></th>
<th <?if($classmark['periodical'] == '1'){echo "class='grey_color thLocation'";}?>><?=$this->translate('Level')?></th>
<th class="thLocation"><?=$this->translate('Book stack number')?></th>
<?endif;?>
</tr>
</thead>
<tbody>
 
<?foreach($this->locations as $location):?>
<?if($classmark['id_classmark']==$location['id_classmark']):?>
<tr>
<td><?=$location['name'];?></td>
<td><?=$location['level'];?></td>
<td><?=$location['stack'];?></td>   
<?if($location['periodical'] == '1'):?>
<td class="width5"></td>
<td><?=$location['periodical_name'];?></td>
<td><?=$location['periodical_level'];?></td>
<td><?=$location['periodical_stack'];?></td>
<?endif;?>
</tr>
<?endif;?>
<?endforeach;?>
</tbody>
</table>
<p><a href="<?='#'.$classmark['name']?>"><?=$this->translate('Back to Top')?></a></p>
<?endforeach;?>
<?endif;?>
</div>    
<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->render("locationlist/menu.phtml")?>
</div>