<? $manuscript = $this->driver->userPermissions('Manuscript'); ?>
<?
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }

  $formatRoles = function ($roles) {
    if (count($roles) == 0) {
      return '';
    }
    $that = $this;
    $translate = function ($str) use ($that) {
      return $that->transEsc('CreatorRoles::' . $str);
    };
    return ' (' . implode(', ', array_unique(array_map($translate, $roles))) . ')';
  };
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3 img-col hidden">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-12 info-col">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

    <h3 property="name"><?=$this->escapeHtml(html_entity_decode($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection(), ENT_QUOTES | ENT_HTML5))?></h3>

	     <? $lnkTitle = $this->driver->getLinkedTitle();if (!empty($lnkTitle)): ?>
   
          <? foreach($lnkTitle as $field): ?>
            <h4><?=$this->escapeHtml($field)?></h4>
          <? endforeach; ?>

      <? endif; ?> 
	
		<? $codex = $this->driver->getClassmark(); ?>
		<? if ($codex): ?>
			<p><strong>In codex:</strong> <?=$this->escapeHtml($codex)?></p>
		<? endif; ?>
	
    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? html_entity_decode($this->escapeHtml($summary[0]), ENT_QUOTES | ENT_HTML5)  : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>
    
    
	<?
		$classmark = $this->driver->getClassmark();
		$availability = $this->driver->getAvailability();
		$availability_status = $this->driver->getAvailabilityStatus();
	?>
		
	<script>
			$(document).ready(function(){
			$("#tooltip-ex a").tooltip({
			placement : 'top'
			});
			});
	</script>
	<div class="holdings">
	<table class="table table-responsive" summary="<?=$this->transEsc('manuscript access')?>">
	<tr class="hidden_holdings2">
	
	<td id="boxArchive" class="col-sm-3"><div id="tooltip-ex"><a target="_blank" href="/Locationlist?ll=Archives xxxxx Special Collections&cm=<?=$classmark?>" data-toggle="tooltip" data-original-title="<?=$this->transEsc("Archive & Special Collections")?>"><?=$this->transEsc("Archive & Special Collections")?></a></div></td>
	
	<? if (!empty($classmark)): ?>
		<td id="boxClassmark" class="col-sm-3"><?=$classmark?></td>
	<? endif; ?>
	
	<td id="boxLoanType" class="col-sm-3"><div id="tooltip-ex"><a href="https://www.soas.ac.uk/library/archives/services/requesting-material/" data-toggle="tooltip" data-original-title="<?=$this->escapeHtml($availability[0])?>"><?=$this->transEsc("Reference only")?></a></div></td>
	
	<? if (!empty($availability_status)): ?>
		<? foreach ($availability_status as $field): ?>
			<?if($this->escapeHtml($field) == "restricted"):?>
				<td id="boxAccess" class="text-danger col-sm-3"><?=$this->escapeHtml(ucfirst($field))?></td>
			<?else:?>
				<td id="boxAccess" class="text-success col-sm-3"><?=$this->transEsc("Available")?></td>
			<?endif;?>
		<? endforeach; ?>
    <? endif; ?>
	
	</tr>
	</table>
	
	<? if (!empty($availability_status)): ?>
		<? foreach ($availability_status as $field): ?>
			<?if($this->escapeHtml($field) == "restricted"):?>
				<? if (!empty($availability)): ?>
					<table><tr><td id="manuscript_note"><?=$this->escapeHtml($availability[0])?><td></tr></table>
				<?endif;?>
			<?endif;?>
		<? endforeach; ?>
    <? endif; ?>
	
	<? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
          but even if we don't plan to display the link, we still want to get the $openUrl
          value for use in generating a COinS (Z3988) tag -- see bottom of file.
        */
        $openUrl = $this->openUrl($this->driver, 'results');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

		if ((!empty($urls) || $openUrlActive) && (strpos($urls[0]['url'],'digital.soas.ac.uk') !== false)): ?>
			<table class="table table-responsive">
				<? if ($openUrlActive): ?>
					<br/>
					<?=$openUrl->renderTemplate()?>
				<? endif; ?>
				<? if (!is_array($urls)) $urls = array();
					if(!$this->driver->isCollection()):
						foreach ($urls as $current): ?>
							<? if($this->driver->getRegExpr($this->escapeHtml($current['desc']), $collectionType,$this->driver->getCollectionType()[0])): ?>										  
								<tr>
									<td><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->transEsc("click_here_for_full_text")?></a>
									</td>
								</tr>
							<? else: ?>
								<tr>
									<td><?=$this->transEsc("Not available")?></td>
								</tr>
							<? endif; ?>
						<? endforeach; ?>
					<? endif; ?>
				<? endif; ?>
			</table>
	</div>	

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
    
      <? $order = $this->driver->getOrderWith(); if (!empty($order) && count($order)>0 && !empty($order[0])): ?>
      <tr>
        <th><?=$this->transEsc('Order Number')?>:</th>
        <td>
            <? foreach ($order as $orderAux): ?><?= html_entity_decode($this->escapeHtml($orderAux), ENT_QUOTES | ENT_HTML5)?><br/><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      
      <? $dateCreation = $this->driver->getDateCreation(); if (!empty($dateCreation) && count($dateCreation)>0 && !empty($dateCreation[0])): ?>
      <tr>
        <th><?=$this->transEsc('dates_creation')?>:</th>
        <td>
            <? foreach ($dateCreation as $dateAux): ?><?= $this->escapeHtml($dateAux)?><br/><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
    
     <? $level = $this->driver->getLevel(); if (!empty($level) && count($level)>0  && !empty($level[0])): ?>
      <tr>
        <th><?=$this->transEsc('Level')?>:</th>
        <td>
            <? foreach ($level as $levelAux): ?><?= html_entity_decode($this->escapeHtml($levelAux), ENT_QUOTES | ENT_HTML5)?><br/><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=str_replace('class="', 'class="label label-info ', $this->record($this->driver)->getFormatList())?>
                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	       <?if($this->driver->getElectronic()== "Electronic"):?>
	       <span class="label label-info iconlabel electronic"><?=$this->transEsc("Electronic")?></span>
	       <?endif;?>
          </td>
        </tr>
      <? endif; ?>
	  
	  <? $level = $this->driver->getForm(); if (!empty($level)): ?>
      <tr>
        <th><?=$this->transEsc('Level')?>:</th>
        <td>
            <?=$this->escapeHtml(ucfirst($level))?><br/>
        </td>
      </tr>
      <? endif; ?>
      
      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $alttitle = $this->driver->getAltTitle(); if (!empty($alttitle)): ?>
      <tr>
        <th><?=$this->transEsc('Alternative Titles')?>: </th>
        <td>
          <? foreach($alttitle as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
		  <? $linkedalttitle = $this->driver->getLinkedTitleAlt(); if (!empty($linkedalttitle)): ?>
			<? foreach($linkedalttitle as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
			<? endforeach; ?>
		  <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

   <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <tr>
          <th><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </th>
          <td>
            <? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':', '?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><?=$formatRoles($roles)?></span><? endforeach; ?><br/>
			<? $linkedauthor = $this->driver->getLinkedAuthor(); if (!empty($linkedauthor)): ?>
				<? foreach($linkedauthor as $field): ?>
					<a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a>
					<br />
				<? endforeach; ?>
			<? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
        <tr>
          <th><?=$this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Author' : 'Corporate Authors')?>: </th>
          <td>
            <? $i = 0; foreach ($authors['corporate'] as $corporate => $roles): ?><?=($i++ == 0)?'':', '?><span property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $corporate)?>"><?=$this->escapeHtml($corporate)?></a><?=$formatRoles($roles)?></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
        <tr>
          <th><?=$this->transEsc('Other Authors')?>: </th>
          <td>
            <? $i = 0; foreach ($authors['secondary'] as $author => $roles): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><?=$formatRoles($roles)?></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

	  <? $language = $this->driver->getLanguages(); if (!empty($language)): ?>
      <tr>
        <th><?=$this->transEsc('Language')?>: </th>
        <td>
            <? foreach ($language as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

	  <? $note = $this->driver->getNote(); if (!empty($note)): ?>
      <tr>
        <th><?=$this->transEsc('Note')?>: </th>
        <td>
            <? foreach($note as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $incipit = $this->driver->getIncipit(); if (!empty($incipit)): ?>
      <tr>
        <th><?=$this->transEsc('Incipit')?>: </th>
        <td>
            <? foreach($incipit as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $explicit = $this->driver->getExplicit(); if (!empty($explicit)): ?>
      <tr>
        <th><?=$this->transEsc('Explicit')?>: </th>
        <td>
            <? foreach($explicit as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $colophon = $this->driver->getColophon(); if (!empty($colophon)): ?>
      <tr>
        <th><?=$this->transEsc('Colophon')?>: </th>
        <td>
            <? foreach($colophon as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
	  <? $filiation = $this->driver->getFiliation(); if (!empty($filiation)): ?>
      <tr>
        <th><?=$this->transEsc('Filiation')?>: </th>
        <td>
            <? foreach($filiation as $field): ?>
				<?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
	  
      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td> 
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="place"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
		  
		  <? $linkedimprint = $this->driver->getLinkedImprint(); if (!empty($linkedimprint)): ?>
              <? foreach ($linkedimprint as $field): ?><?= $this->escapeHtml($field)?><br/>
			  <? endforeach; ?>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>
      
      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if ((!empty($urls) || $openUrlActive) && (strpos($urls[0]['url'],'digital.soas.ac.uk') !== false)): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <? if($this->driver->getRegExpr($this->escapeHtml($current['desc']), $archive)): ?>
				<? if(strpos($this->proxyUrl($current['url']),'digital.soas.ac.uk') !== false): ?>
					<a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
				<? endif; ?>
            <? else: ?>
				<span><?=$this->transEsc("Not available")?></span></br>
            <?endif;?>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

       <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
      
</br>
<script>
function showAllHoldings() {
$( ".hidden_holdings" ).each(function() {
  $( this ).removeClass( "hidden_holdings" ).addClass( "hidden_holdings3" );
});

$( "#div_show_more" ).each(function() {
  $( this ).addClass( "hidden" );
});
$( "#div_show_less" ).each(function() {
  $( this ).removeClass( "hidden" );
});
}

function showLessHoldings() {
$( ".hidden_holdings3" ).each(function() {
	
  $( this ).removeClass( "hidden_holdings3" ).addClass( "hidden_holdings" );
  
  $( "#div_show_less" ).each(function() {
  $( this ).addClass( "hidden" );
});
$( "#div_show_more" ).each(function() {
  $( this ).removeClass( "hidden" );
});
});

}
</script>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
</br>
