<?
  // Set page title.
  $this->headTitle($this->translate('Electronic resources'));
  
  // Set up breadcrumbs:
  if(!empty($this->resource) && $this->act_type == '1'):
  	$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/accesstypes') . '">' . $this->transEsc('Administration') . '</a></li><li><a href="' . $this->url('acadmin/electronicresources') . '">' . $this->transEsc('Electronic resources') . '</a></li> <li><a href="' . $this->url('acadmin/resource') . '?res='. $this->resource . '">' . $this->resource . '</a></li> <li class="active">' . $this->transEsc('Edit') . '</li>';
  elseif(!empty($this->resource) && $this->act_type == '2'):
  	$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/accesstypes') . '">' . $this->transEsc('Administration') . '</a></li><li><a href="' . $this->url('acadmin/electronicresources') . '">' . $this->transEsc('Electronic resources') . '</a></li> <li><a href="' . $this->url('acadmin/resource') . '?res='. $this->resource . '">' . $this->resource . '</a></li> <li class="active">' . $this->transEsc('Add') . '</li>';
  else:
  	$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li><li><a href="' . $this->url('acadmin/accesstypes') . '">' . $this->transEsc('Administration') . '</a></li> <li><a href="' . $this->url('acadmin/electronicresources') . '">' . $this->transEsc('Electronic resources') . '</a></li> <li class="active">' . $this->resource . '</li>';
  endif;
?>
<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Electronic resources')?></h2>

<? if ($this->action == '1'): ?>
<div class="alert alert-success">
  <strong>Success!</strong> The settings were saved.
</div>
<? elseif ($this->action == '2'): ?>
<div class="alert alert-danger">
  <strong>Danger!</strong> Error.
</div>
<? elseif ($this->action == '3'): ?>
<div class="alert alert-danger">
  <strong>Danger!</strong> Anyone changes the file.
</div>
<? endif; ?>

<? if ($this->act_type == 0) { ?>

<form method="post" action="/Acadmin/Resource?res=<?=$this->resource?>" name="deleteForm" id="deleteForm">

<div id="locationPanel">
<a  class="btn btn-customized" href="/Acadmin/Resource?res=<?=$this->resource?>&add=1"><?=$this->transEsc('Add')?></a>
<input value="Delete" id="deleteButton" name="deleteButton" type="button" class="btn btn-customized"/> 
</div> 
<table class="GeneratedTable">
<thead>
<tr>
<th class="thLocation"></th>
<th class="thLocation"><?=$this->translate('URLs')?></th>
 </tr>
</thead>
<tbody>

<? for ($i = 0; $i < count($this->regex); $i++) { ?>
	<tr>
	<? /* <td><input type="checkbox" name="check[]" id="<?=$i?>" value="<?=$this->regex[$i];?>"></td> */ ?>
	<td><input type="checkbox" name="check[]" id="<?=$i?>" value="<?=$i;?>"></td>
	<td><a href="/Acadmin/Resource?res=<?=$this->resource?>&pos=<?=$i?>"><?=$this->regex[$i];?></a></td>
	</tr>
<? } ?>

 </tbody>
</table>

<input type="hidden" name="delete" id="delete" value="0"/>
<input type="hidden" name="readDate" id="readDate" value="<?=$this->readDate?>"/>

<?
$file = '/usr/local/vufind/local/config/vufind/electronicResources.ini';
if (file_exists($file)) {
	$afterDelDate = date ("F d Y H:i:s.", filemtime($file));
}
?>

</form>

<? } else if($this->act_type == 1) { ?>
	<form method="post" action="/Acadmin/Resource?res=<?=$this->resource?>" name="editForm" id="editForm">
		<div class="form-group">
			<label for="URL">Regular expression</label>
		</div>
		<div class="form-group">
			<input type="text" class="form-control" placeholder="URL" id="RegExp" name="RegExp" value="<?=$this->regex;?>">
		</div>
		<input value="Edit" id="editButton" name="editButton" type="button" class="btn btn-customized"/>
		<input type="hidden" name="pos" id="pos" value="<?=$this->position;?>"/>
		<input type="hidden" name="edit" id="edit" value="0"/>
		<input type="hidden" name="readDate" id="readDate" value="<?=$this->readDate?>"/>
	</form>
<? } else if($this->act_type == 2) { ?>
	<form method="post" action="/Acadmin/Resource?res=<?=$this->resource?>" name="addForm" id="addForm">
		<div class="form-group">
			<label for="URL">Regular expression</label>
		</div>
		<div class="form-group">
			<input type="text" class="form-control" placeholder="URL" id="RegExp" name="RegExp" value="">
		</div>
		<input value="Add" id="addButton" name="addButton" type="button" class="btn btn-customized"/>
		<input type="hidden" name="add" id="add" value="0"/>
		<input type="hidden" name="readDate" id="readDate" value="<?=$this->readDate?>"/>
	</form>
<? } ?>

  </div>
<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->render("acadmin/menu.phtml")?>
</div>
</div>

<script>
$(document).ready(function(){

/* To save the data */

	$('#delete').val("0");
	$("#deleteButton").click(function() {
		$('#readDate').val("<?=$afterDelDate?>");
	    bootbox.confirm({
	        message: "Do you want to delete the URLs?",
	        buttons: {
	            confirm: {
	                label: 'Yes',
	                className: 'btn-success'
	            },
	            cancel: {
	                label: 'No',
	                className: 'btn-danger'
	            }
	        },
	        callback: function (result) {
	            if(result) {
	            	$('#delete').val("1");
	            	$("#deleteForm").submit();
	            }
	        }
	    });
	});
	

/* To edit the data */

	$('#edit').val("0");
	$("#editButton").click(function() {
	    bootbox.confirm({
	        message: "Do you want to edit the URL?",
	        buttons: {
	            confirm: {
	                label: 'Yes',
	                className: 'btn-success'
	            },
	            cancel: {
	                label: 'No',
	                className: 'btn-danger'
	            }
	        },
	        callback: function (result) {
	            if(result) {
	            	$('#edit').val("1");
	            	$("#editForm").submit();
	            }
	        }
	    });
	});

/* To add a resource */

	$('#add').val("0");
	$("#addButton").click(function() {
	    bootbox.confirm({
	        message: "Do you want to add the URL?",
	        buttons: {
	            confirm: {
	                label: 'Yes',
	                className: 'btn-success'
	            },
	            cancel: {
	                label: 'No',
	                className: 'btn-danger'
	            }
	        },
	        callback: function (result) {
	            if(result) {
	            	$('#add').val("1");
	            	$("#addForm").submit();
	            }
	        }
	    });
	});

});
</script>