<?
  // Set page title.
  $this->headTitle($this->translate('Finding materials in the library'));      
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('locationlist') . '">' . $this->transEsc('Finding materials in the library') . '</a></li>';
?>
<div id="content" class="container">
<div class="row-fluid">  

<h3><?=$this->transEsc('Classmark by first letter')?></h3>
<?if(!empty($this->classmarks)):?>    
<?foreach($this->classmarks as $classmark):?>
<a id="<?=$classmark['id_classmark'];?>" <?if($this->classmark['id_classmark'] == $classmark['id_classmark']) { echo "class='classmark_letter soasColor'"; }else{ echo "class='classmark_letter'";}?>  href="<?=$this->url('locationlist/location').'?id_classmark='.$classmark['id_classmark']?>"><?=$classmark['name'];?></a>
<?endforeach?>
<?endif;?>
<br><br>
<h3><?=$this->transEsc('Classmarks by library location')?></h3>
<?if(!empty($this->levels)):?>    
<?foreach($this->levels as $level):?>
<a id="<?=$level['id_level'];?>" <?if($this->id_level == $level['id_level']) { echo "class='classmark_letter soasColor'"; }else{ echo "class='classmark_letter'";}?>  href="<?=$this->url('locationlist/location').'?id_level='.$level['id_level'].'&order=2'?>"><?=$level['name'];?></a>
<?endforeach?>
<?endif;?>
<br><br><br> 
<?
 	$cm = "";
    	$ll = "";
    	$warning_text = "";
	if (isset($_GET['cm'])) {
		$cm = $_GET['cm'];
		$arr_cm = explode("/",$cm);
		if($arr_cm[0] != "")$cm = $arr_cm[0];
	}
    	
	if (isset($_GET['ll'])) {
    		$ll = $_GET['ll'];
    		if($ll !=""){
    			foreach($this->levels as $levelAux){if(str_replace("xxxxx","&",$ll) == $levelAux['name']){$id_level=$levelAux['id_level'];}}    			
    		}
    	}
    	if($ll != "" || $cm != ""){
    		$warning_text = '<h4>'.$this->transEsc('Your search').": </h4><br>";
    		if($ll != "")
    			$warning_text = $warning_text.$this->transEsc('Library Location').': <b>'.str_replace("xxxxx","&",$ll).'</b><br>';
    		if($cm != "")
    			$warning_text = $warning_text.$this->transEsc('Call Number').': <b>'.$cm.'</b>';    		
    	}
	
?>
<?if($warning_text != ""):?><div class="alert alert-warning"><?=$warning_text?></div><?endif;?>
<br>
<div><?=$this->description;?></div>
<br>
</div>
</div>
