<?
    // Set page title.
    $this->headTitle($this->translate('Author'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Author') . '</li>';
?>
<form class="form-inline" method="get" action="<?=$this->url('author-search')?>">
  <label for="author_lookfor"><?=$this->transEsc('Author Results for')?>:</label></br>
  <input class="form-control" type="text" id="author_lookfor" name="lookfor" />
  <!--<input class="btn btn-default" type="submit" value="<?=$this->transEsc('Find')?>" />-->
  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?=$this->transEsc("Find")?></button>
</form>
