<div class="list-group">
  <a href="<?=$this->url('acadmin/accesstypes')?>" class="list-group-item<?=strtolower($this->layout()->templateName) == "accesstypes" ? ' active' : ''?>"><?=$this->transEsc('Access types')?></a>
  <a href="<?=$this->url('acadmin/accesspermissions')?>" class="list-group-item<?=strtolower($this->layout()->templateName) == "accesspermissions" ? ' active' : ''?>"><?=$this->transEsc('Access permissions')?></a>
  <a href="<?=$this->url('acadmin/electronicresources')?>" class="list-group-item<?=strtolower($this->layout()->templateName) == "electronicresources" ? ' active' : ''?>"><?=$this->transEsc('Electronic resources')?></a>
  <a href="<?=$this->url('acadmin/locations')?>" class="list-group-item<?=strtolower($this->layout()->templateName) == "locations" ? ' active' : ''?>"><?=$this->transEsc('Location list')?></a>
</div>
