<? $account = $this->auth()->getManager(); ?>
<?
/* Access permissions */
$online_access = $account->userPermissions('Online Resources');
?>
<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $ignoreHiddenFilterMemory = isset($this->ignoreHiddenFilterMemory) && $this->ignoreHiddenFilterMemory;
    $ignoreHiddenFiltersInRequest = isset($this->ignoreHiddenFiltersInRequest) && $this->ignoreHiddenFiltersInRequest;
    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
    if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
        $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
        if (empty($hiddenFilters)) {
            $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId);
        }
    }
    $hiddenFilterParams = $this->searchtabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');
?>

<? if ($this->searchType == 'advanced'): ?>
<!-- Edited by sb174 on 2018-02-18 -->
<!--   <div class="searchForm navbar-form navbar-left flip">
    <? $tabs = $this->context($this)->renderInContext('search/searchTabs', ['hiddenFilters' => $hiddenFilters]); ?>
    <? if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><? endif; ?>
      <p class="adv_search_terms"><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"</p>
      <p class="adv_search_links">
        <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
        <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?></a> |
        <a href="<?=$this->url($searchHome) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Basic Search")?></a>
      </p>
    <? if (!empty($tabs)): ?></div><? endif; ?>
  </div> -->

  <form id="searchForm" class="searchForm col-md-8 navbar-form navbar-left" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <?= $this->context($this)->renderInContext('search/searchTabs', ['hiddenFilters' => $hiddenFilters]); ?>
    <div><input id="searchBox" tabindex="1" class="box searchForm_lookfor form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>" placeholder="<?=$this->transEsc("Search SOAS Library")?>" required>
    <? if ($handlerCount > 1): ?>
    <!--<select class="searchForm_type form-control box" name="type" data-native-menu="false">
        <? foreach ($handlers as $handler): ?>
          <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
        <? endforeach; ?>
      </select>-->
      
    <? elseif ($handlerCount == 1): ?>
      <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
    <? endif; ?>
    <button id="btnFind" type="submit" class="btn btn-primary box"><i class="fa fa-search" aria-hidden="true"></i> <?=$this->transEsc("Find")?></button>

    <div id="divSearch" class="col-md-12 hidden-xs hidden-sm">
    <div class="radioHome"><label class="radioSearch"><input id="rdAll" type="radio" name="filter[]" value='*:*' checked="checked"><?=$this->transEsc('All collections')?></label></input></div>
    <div class="radioHome"><label class="radioSearch"><input id="rdBook" type="radio" name="filter[]" value='-collection:"SOAS Archive"'/><?=$this->transEsc('Print, books, and media')?></label></input></div>
    <? if (!$online_access) { ?>
    	<div class="radioHome"><label class="radioSearch"><input id="rdOnline" type="radio" name="filter[]" value="Online" onclick="openEds();"/><?=$this->transEsc('Online resources')?></label></input></div>
    <?}?>
    <div class="radioHome"><label class="radioSearch"><input id="rdArchive" type="radio" name="filter[]" value='collection:"SOAS Archive"' /><?=$this->transEsc('Archives')?></label></input></div>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <div class="checkbox col-md-4 hidden-xs hidden-sm" style="float:right;">
        <label>
          <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </div>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <? foreach ($hiddenFilters as $key => $filter): ?>
      <? foreach ($filter as $value): ?>
        <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
      <? endforeach; ?>
    <? endforeach; ?>
    </div>    
    
    <div id="divSearch" class="col-md-9 hidden-md hidden-lg">
    <div class="radioHome"><label class="radioSearch"><input id="rdBook" type="radio" name="filter[]" value='*:*' checked="checked"/><?=$this->transEsc('Books')?></label></input></div>
    <? if (!$online_access) { ?>
 	   <div class="radioHome"><label class="radioSearch"><input id="rdOnline" type="radio" name="filter[]" value="Online" onclick="openEds();"/><?=$this->transEsc('Online')?></label></input></div>
    <?}?>
    <div class="radioHome"><label class="radioSearch"><input id="rdArchive" type="radio" name="filter[]" value='collection:"SOAS Archive"' /><?=$this->transEsc('Archives')?></label></input></div>
    </div>

    <p class="adv_search_links">
        <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
        <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?></a> |
        <a href="/"><?=$this->transEsc("Start a new Basic Search")?></a>
    </p>
<!-- END -->
<? else: ?>
  <form id="searchForm" class="searchForm col-md-8 navbar-form navbar-left" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <?= $this->context($this)->renderInContext('search/searchTabs', ['hiddenFilters' => $hiddenFilters]); ?>
    <div><input id="searchBox" tabindex="1" class="box searchForm_lookfor form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>" placeholder="<?=$this->transEsc("Search SOAS Library")?>" required>
    <? if ($handlerCount > 1): ?>
      <select class="searchForm_type form-control box" name="type" data-native-menu="false">
        <? foreach ($handlers as $handler): ?>
          <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
        <? endforeach; ?>
      </select>
      
    <? elseif ($handlerCount == 1): ?>
      <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
    <? endif; ?>
    <button id="btnFind" type="submit" class="btn btn-primary box"><i class="fa fa-search" aria-hidden="true"></i> <?=$this->transEsc("Find")?></button>

    <!--Commented out 2017-11-08 by sb174 to return Advanced link to home page-->
    <?# if ($this->url() !="/") :?>
        <? if ($advSearch): ?>
            <a href="<?=$this->url($advSearch) . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams) ?>" class="btn btn-link" rel="nofollow"><?=$this->transEsc("Advanced")?></a>
        <? endif; ?>
    <?# endif; ?>

    <? if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
        <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
    <? endif; ?>
</div>
  
    <div id="divSearch" class="col-md-12 hidden-xs hidden-sm">
    <div class="radioHome"><label class="radioSearch"><input id="rdAll" type="radio" name="filter[]" value='*:*' checked="checked"><?=$this->transEsc('All collections')?></label></input></div>
    <div class="radioHome"><label class="radioSearch"><input id="rdBook" type="radio" name="filter[]" value='-collection:"SOAS Archive"'/><?=$this->transEsc('Print, books, and media')?></label></input></div>
    <? if (!$online_access) { ?>
	    <div class="radioHome"><label class="radioSearch"><input id="rdOnline" type="radio" name="filter[]" value="Online" onclick="openEds();"/><?=$this->transEsc('Online resources')?></label></input></div>
    <?}?>
    <div class="radioHome"><label class="radioSearch"><input id="rdArchive" type="radio" name="filter[]" value='collection:"SOAS Archive"' /><?=$this->transEsc('Archives')?></label></input></div>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <div class="checkbox col-md-4 hidden-xs hidden-sm" style="float:right;">
        <label>
          <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </div>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <? foreach ($hiddenFilters as $key => $filter): ?>
      <? foreach ($filter as $value): ?>
        <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
      <? endforeach; ?>
    <? endforeach; ?>
    </div>    
    
    <div id="divSearch" class="col-md-9 hidden-md hidden-lg">
    <div class="radioHome"><label class="radioSearch"><input id="rdBook" type="radio" name="filter[]" value='*:*' checked="checked"/><?=$this->transEsc('Books')?></label></input></div>
    <? if (!$online_access) { ?>
	    <div class="radioHome"><label class="radioSearch"><input id="rdOnline" type="radio" name="filter[]" value="Online" onclick="openEds();"/><?=$this->transEsc('Online')?></label></input></div>
    <?}?>
    <div class="radioHome"><label class="radioSearch"><input id="rdArchive" type="radio" name="filter[]" value='collection:"SOAS Archive"' /><?=$this->transEsc('Archives')?></label></input></div>
    </div>

    <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
      <br />
      <? foreach ($shards as $shard => $val): ?>
        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
      <? endforeach; ?>
    <? endif; ?>
<!--     <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
      <div class="checkbox">
        <label>
          <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
          <?=$this->transEsc("basic_search_keep_filters")?>
        </label>
      </div>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <? foreach ($hiddenFilters as $key => $filter): ?>
      <? foreach ($filter as $value): ?>
        <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
      <? endforeach; ?>
    <? endforeach; ?> -->
    <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
  </form>
  <script type="text/javascript">$(".searchForm_lookfor:visible").focus()</script>
<? endif; ?>


<script>

var URLactual = window.location.href;
document.getElementById("rdAll").checked=true; 
if (URLactual.indexOf('-collection%3A%22SOAS+Archive%22')>0) { 
    document.getElementById("rdBook").checked=true;
}
else { 
    if (URLactual.indexOf('collection%3A%22SOAS+Archive%22')>0) {
        document.getElementById("rdArchive").checked=true;
     }
     else {
         document.getElementById("rdAll").checked=true; 
     }
}




function openEds(){
        var search = encodeURIComponent($('#searchForm_lookfor').val());

        if(search !="Undefined" && search !="undefined" && search == '') {
                window.open('https://search.ebscohost.com/login.aspx?authtype=ip,cookie,shib&custid=s8438947&groupid=main&profile=eds&direct=true&type=0&site=eds-live&bquery='+search);
        }
        else{
                 window.open('https://search.ebscohost.com/login.aspx?authtype=ip,cookie,shib&custid=s8438947&groupid=main&profile=eds');
        }
}
</script>
