<h1>About</h1>

<ul class="HelpMenu">
  <li><a href="#Contents">Contents</a></li>
  <li><a href="#Software">Software</a></li>
  <li><a href="#Development">Development</a></li>
</ul>

<dl class="Content">
  <dt><a name="Contents"></a>Contents</dt>
  <dd>
    <p><a href="/">library.soas.ac.uk</a> finds records of books, periodicals, and some research articles from SOAS Library's catalogue and from <a href="http://eprints.soas.ac.uk">SOAS Research Online</a>.</p>
    <p>Copyright and other intellectual property rights in these web pages belongs to SOAS unless otherwise indicated. Where copyright belongs to SOAS, content on this website is licensed for use under a <a href="http://creativecommons.org/licenses/by-nc-nd/2.0/uk/">Creative Commons Attribution-Non-Commercial-No Derivative Works 2.0 UK: England & Wales Licence (CC BY-NC-ND 2.0)</a> unless the individual resource states otherwise.</p>
    <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/2.0/uk/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/2.0/uk/88x31.png" /></a></p>
  </dd>
  
  <dt><a name="Software"></a>Software</dt>
  <dd>
    <p>This library catalogue runs on VuFind version 2.3. <a href="https://vufind-org.github.io/vufind/">VuFind</a> is open-source search engine and resource discovery software for libraries. VuFind was designed by <a href="http://library.villanova.edu/">Villanova University's Falvey Memorial Library</a> and is distributed under the <a href="https://gnu.org/licenses/gpl.html">GNU General Public License</a>.</p>
    <p>Library data is stored in SOAS Library's Kuali OLE library management system. <a href="http://www.kuali.org/ole">OLE (Open Library Environment)</a> is an open-source library management system from the <a href="https://www.kuali.org/">Kuali Foundation</a> and is distributed under the <a href="http://opensource.org/licenses/ecl2.php">Educational Community License Version 2.0 (ECL-2.0)</a>.</p>
  </dd>

  <dt><a name="Development"></a>Development</dt>
  <dd>
    <p>SOAS Library's catalogue was developed by <a href="mailto:library.systems@soas.ac.uk">Simon Barron</a>, Analyst Programmer (Library Systems), and is maintained by the Corporate Systems & Business Services (CSBS) team of the <a href="https://www.soas.ac.uk/lis/">Library & Information Services Directorate (LIS)</a>.</p>
  </dd>
</dl>
