<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  
  <? $accessnote = $this->driver->getNote(); if (!empty($accessnote)): ?>
    <? foreach ($accessnote as $field): ?>
 	<?if (stripos($field, 'Off-campus access') !== false): ?>
	   <?= $this->escapeHtml($field)?>
      	   <br />
      	<? endif; ?>
    <? endforeach; ?>
    <br />
  <? endif; ?>
  
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
<? endif; ?>

<?=$this->ils()->getJournalStatus() ?>

<?=$this->ils()->getOrderStatus()?>

<? foreach ($holdings as $holding): ?>
<h3><a href="http://www.soas.ac.uk/library/using/finding/location/"><?=$this->transEsc($holding['location'])?></a></h3>

<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <? if (!empty($holding['summary'])): ?>
  <tr>
    <th><?=$this->transEsc("Volume Holdings")?>: </th>
    <td>
      <? foreach ($holding['summary'] as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['notes'])): ?>
  <tr>
    <th><?=$this->transEsc("Notes")?>: </th>
    <td>
      <? foreach ($holding['notes'] as $data): ?>
        <?=$this->escapeHtml($data)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  
  <? foreach ($holding['items'] as $row): ?>
    <?
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      
      // AJAX block record?
      $block = !$check && isset($row['addLink']) && $row['addLink'] === 'block';
      $blockStorageRetrievalRequest = !$checkStorageRetrievalRequest && isset($row['addStorageRetrievalRequestLink']) && $row['addStorageRetrievalRequestLink'] === 'block';
      $blockILLRequest = !$checkILLRequest && isset($row['addILLRequestLink']) && $row['addILLRequestLink'] === 'block';
    ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <!--<th class="hidden-xs"><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>-->
        <td class="hidden-xs">
        <? if ($row['holdings']): ?> <?=$this->escapeHtml($row['holdings'])?>
        <? endif; ?>
        </td>
        <td>
      <? if ($row['callnumber']): ?> <strong class="hidden-xs"><?=$this->transEsc("Call Number")?>:</strong> <a href="/Alphabrowse/Home?source=callnumber&from=<?=$this->escapeHtml($row['callnumber'])?>"><?=$this->escapeHtml($row['callnumber'])?></a>
        <? endif; ?>
        </td>
        <td class="hidden-xs">
		<script>
			$(document).ready(function(){
			$("#tooltip-ex a").tooltip({
			placement : 'top'
			});
			});
		</script>
        <? if ($row['loan_period']): ?>
			<? if (stripos($row['loan_period'], 'LONG LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Anyone with SOAS Library membership can borrow this item type")?>"><?=$this->escapeHtml($row['loan_period'])?></a>
			<? elseif (stripos($row['loan_period'], 'ONE WEEK LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only SOAS staff and students can borrow this item type")?>"><?=$this->escapeHtml($row['loan_period'])?></a>
			<? elseif (stripos($row['loan_period'], '3 DAY LOAN') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only SOAS staff and students can borrow this item type")?>"><?=$this->escapeHtml($row['loan_period'])?></a>
			<? elseif (stripos($row['loan_period'], 'REFERENCE ONLY') !== false): ?>
			<div id="tooltip-ex">
			<a href="#" data-toggle="tooltip" 
			data-original-title="<?=$this->transEsc("Only for use in the library")?>"><?=$this->escapeHtml($row['loan_period'])?></a>
			<? else: ?>
			<?=$this->escapeHtml($row['loan_period'])?>
			<? endif; ?>
        <? endif; ?>
		</td>
        <td>
        <?=$this->escapeHtml($row['collection'])?>
        </td>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <a style="display:inline-block" class="<?=$check ? 'checkRequest ' : ''?>inlineblock modal-link placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" title="<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?>"><i class="icon-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?>modal-link placeStorageRetrievalRequest" href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" title="<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?>"><i class="icon-flag"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="text-danger"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> modal-link inlineblock placehold" href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="icon-flag"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtml($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtml($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtml($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>

  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
